### ISSUE TITLE
Assistance with automation. 

### ISSUE THREAD

**Issue by Merril-r** [georgezhao2010/midea_ac_lan#177]
Hello there.

I have managed to setup the integration and setup an automation to turn the ac on and off as well as one to set it to fan mode.

I would appreciate assistance with setting up a routine to put the ac in eco mode. 

I can’t seem to find the correct options in the automation under the presets. 

Could you provide me with the steps to set this up or the yaml code to do this. On the remote and on the integration I can select eco mode and it is activated with the preset temp of 24. 

Any assistance will greatly be appreciated.

**Comment by IGaMbLeRI** [comment]
I have the following automation turning on ECO mode via the provided switch (Integration -> Configure -> activate ECO switch):
````
alias: GENERAL - Bedroom - A/C COOL ECO
description: ""
trigger:
  - platform: device
    device_id: dc6ca930c2c56379e535dc9dd45b1eec
    domain: climate
    entity_id: climate.18691697749164_climate
    type: hvac_mode_changed
    to: cool
condition: []
action:
  - type: turn_on
    device_id: dc6ca930c2c56379e535dc9dd45b1eec
    entity_id: switch.18691697749164_eco_mode
    domain: switch
mode: single
````
