### ISSUE TITLE
Custom Fun speed 

### ISSUE THREAD

**Issue by maciey** [georgezhao2010/midea_ac_lan#223]
Can you please add option to enter precise value for fan speed?
(I mean not only low /mid / high etc - but entering eg 5%)

Mobile app allows that

I do have Rotenso AC

**Comment by maciey** [comment]
Found this is already implemented :)

Below works to me 

```
service: midea_ac_lan.set_ac_fan_speed
data:
  device_id: xxxxx
  fan_speed: 5
```
