### ISSUE TITLE
Custom fan speed doesn't work properly. 

### ISSUE THREAD

**Issue by msdurex** [georgezhao2010/midea_ac_lan#344]
### HA core version

2023.4.2

### Intergration version

0.3.18

### Device type and model

Air Conditioner 22012637

### Used App

MSmartHome

### The description of problem

Custom fan speed doesn't work properly. 100 steps adjustment has much smooth user experience. If it's possible to bring back custom fan speed support would be nice.

**Comment by georgezhao2010** [comment]
> ### The description of problem
> Custom fan speed doesn't work properly. 100 steps adjustment has much smooth user experience. If it's possible to bring back custom fan speed support would be nice.
> 
> ### The logs
> _No response_

upgrade to latest release, then follow the documentation https://github.com/georgezhao2010/midea_ac_lan/blob/master/doc/AC.md#services.

**Comment by msdurex** [comment]
I added {"fan_speed":  100} into configure customize section and went back to device control UI. in fan mode. Still 5 steps. I don't know how to get a slider to work just like MSmartHome app.

**Comment by georgezhao2010** [comment]
> I added {"fan_speed": 100} into configure customize section and went back to device control UI. in fan mode. Still 5 steps. I don't know how to get a slider to work just like MSmartHome app.

The document doesn’t mention that fan_speed can be customized, right? Why did you write it like this? I wanted you to look at the Service.set_attribute section.

```yaml
service: midea_ac_lan.set_attribute
data:
  device_id: XXXXXXXXXXXX
  attribute: fan_speed
  value: auto
```

or

```yaml
service: midea_ac_lan.set_attribute
data:
  device_id: XXXXXXXXXXXX
  attribute: fan_speed
  value: 60
```
