### ISSUE TITLE
风扇56011C8T，上下左右摇头不能用

### ISSUE THREAD

**Issue by jjss520** [georgezhao2010/midea_ac_lan#541]
### HA版本

2024.4.4

### 集成版本

0.3.22

### 设备类型及型号

Fan 56011C8T (0)

### 使用的App

美的美居

### 问题详细描述

添加了额外实体，上下和左右摇头，没作用

**Comment by jjss520** [comment]
档位调节也错乱，高档对应风扇的3，但风扇最高12（风扇档位，通过自定义解决了）
风扇自带温度显示，要是能弄出来就更好了

**Comment by sokonboy** [comment]
> 档位调节也错乱，高档对应风扇的3，但风扇最高12（风扇档位，通过自定义解决了） 风扇自带温度显示，要是能弄出来就更好了

我的FGD24UZR遇到了同样的问题，请问怎么自定义啊？

**Comment by xiasi0** [comment]
从日志里扒出来的，只能帮你到这里了，自己的设备去日志里扒拉把。作者怎么不维护了呢
```
service: midea_ac_lan.send_command
data:
  device_id: 210006728410460
  cmd_type: 2
  cmd_body: "000004002903"
```
![1720188009576](https://github.com/georgezhao2010/midea_ac_lan/assets/129178072/c59a1a93-416b-4273-8059-1b5d57f347d6)
