### ISSUE TITLE
Trying to troubleshoot unit unavailable and then immediately available issue in my logs

### ISSUE THREAD

**Issue by mattlward** [georgezhao2010/midea_ac_lan#59]
I have added the debug command to my configuration.yaml and when I attempt to reboot I get the following error and the system will not reboot.

I think it is the old version not being found, after yours worked I uninstalled the previous Midea HACS integration and have not restarted since.

Configuration.yaml entry:
```
logger:
  default: warning
  logs:
     custom_components.midea_ac_lan: debug

climate:
  - platform: midea_ac
    host: 192.168.1.xxx
    id: 12094627960xxx
```
```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:694
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 11:50:30 AM (3 occurrences)
Last logged: 11:53:22 AM

The system cannot restart because the configuration is not valid: Platform error climate.midea_ac - Integration 'midea_ac' not found.
```

Error in integration:
![image](https://user-images.githubusercontent.com/8540074/184547393-2ec7d194-6bd9-41ef-9a01-c7f206eb748a.png)

**Comment by georgezhao2010** [comment]
> I have added the debug command to my configuration.yaml and when I attempt to reboot I get the following error and the system will not reboot.
> 
> I think it is the old version not being found, after yours worked I uninstalled the previous Midea HACS integration and have not restarted since.
> 
> Configuration.yaml entry:
> 
>  ...
> 

remove the following from your configuration.yaml
```
climate:
  - platform: midea_ac
    host: 192.168.1.xxx
    id: 12094627960xxx
```
then restart the HA.
then show the logs
